"""
Recursive Language Model (RLM) scaffold for crypto-research agents.

Implementation of Algorithm 1 from Zhang, Kraska, Khattab "Recursive Language
Models" (Jan 2026). The user prompt P (here: a token's full data corpus) is
loaded as a variable inside a persistent Python REPL. The root LLM (Opus) is
told it can:

    - peek at slices of the variable with normal Python (`prompt[:200]`,
      `df.head()`, `re.findall(...)`),
    - call `sub_lm("...", context=slice)` to delegate dense reading to Sonnet,
    - stitch sub-LM outputs back together programmatically,
    - print FINAL = {...} when ready, which exits the loop.

This prevents the 50–500 KB token-economics dossier per coin (whitepapers +
unlock CSVs + holder snapshots + audit excerpts + emission curves) from
flooding the root model's context. The root only ever sees what it
deliberately fetches via code.

Design choices vs. the paper's Algorithm 2 ("flawed scaffold"):
  - prompt lives as a REPL variable, NOT in the root's context (Flaw #1 fixed)
  - REPL stdout flows into history, NOT generated by the LM (Flaw #2 fixed)
  - sub_lm is invokable programmatically from inside code, NOT only as a
    declared "action" the root verbalizes (Flaw #3 fixed)

Public API:
    run_rlm(
        agent_name: str,
        environment: dict,           # what gets injected as REPL globals
        task: str,                   # the analysis task in natural language
        output_schema: dict,         # JSON shape to coerce final answer into
        max_iters: int = 12,
    ) -> dict

Each agent's analyze.py builds `environment` from its own SQLite + JSON sidecars
and passes it to run_rlm.
"""
from __future__ import annotations

import io
import json
import re
import sys
import textwrap
import traceback
from contextlib import redirect_stdout, redirect_stderr
from typing import Any, Optional

from .llm_client import sub_lm, DEFAULT_ROOT_MODEL
try:
    from anthropic import Anthropic                       # noqa: F401
except ImportError:
    pass


# ────────────────────────────────────────────────────────────────────────
# REPL: a single namespace dict that we keep across iterations. The root
# model is told "this is your environment" and can call list(prompt.keys()),
# import pandas, etc. We pre-load everything the agent passed in plus
# helpers the model is told it can use.
# ────────────────────────────────────────────────────────────────────────

def _build_repl(environment: dict[str, Any]) -> dict[str, Any]:
    """Construct the persistent globals dict for the REPL."""
    g: dict[str, Any] = {}
    # Standard libs the root might need without import:
    g["json"] = json
    g["re"] = re
    # The recursive sub-LLM call. Crucially this is callable directly from the
    # REPL — not delegated through a verbal "action" the root has to spell out.
    def _sub_lm(prompt: str, *, system: Optional[str] = None, max_tokens: int = 4096) -> str:
        return sub_lm(prompt, system=system, max_tokens=max_tokens)
    g["sub_lm"] = _sub_lm
    g["FINAL"] = None
    # Inject the agent's environment last so the agent can override anything.
    g.update(environment)
    return g


def _exec_code(code: str, globals_dict: dict[str, Any]) -> tuple[str, Optional[str]]:
    """
    Execute a code block in the persistent REPL globals. Returns (stdout, error).
    Per Algorithm 1: only stdout is fed back into the root's history — NOT the
    full state of variables — so context grows linearly with what the model
    chose to print, not with the size of the data.
    """
    out_buf, err_buf = io.StringIO(), io.StringIO()
    error: Optional[str] = None
    try:
        with redirect_stdout(out_buf), redirect_stderr(err_buf):
            exec(compile(code, "<rlm>", "exec"), globals_dict)
    except Exception:
        error = traceback.format_exc(limit=4)
    out = out_buf.getvalue()
    err = err_buf.getvalue()
    if err:
        out = (out + "\n--- stderr ---\n" + err).strip()
    return out, error


# ────────────────────────────────────────────────────────────────────────
# Root LLM call. The root model is Opus by default. It receives:
#   1. the system prompt (RLM instructions + agent task + output schema)
#   2. metadata about what's in the REPL (keys, types, sizes — NOT contents)
#   3. the rolling history of (code_emitted, stdout_observed) pairs
# It returns either another code block (continue) or sets FINAL (exit).
# ────────────────────────────────────────────────────────────────────────

_ROOT_SYSTEM = """\
You are the ROOT of a Recursive Language Model (RLM) for crypto research.

Your prompt — the data you must analyze — is NOT in this conversation. It lives
as Python variables in a persistent REPL you control. Each turn, you write a
short Python code block (wrapped in ```python … ```). The REPL executes it and
returns stdout to you. You iterate until you assign your final answer to FINAL.

You have access to:
  • All variables described in the ENVIRONMENT MANIFEST below (peek with
    normal Python — `df.shape`, `len(text)`, `text[:500]`, `df.head()`).
  • A `sub_lm(prompt, system=None)` function that calls Claude Sonnet
    synchronously. USE IT to read dense passages, parse messy CSVs, classify
    lines, summarize sections — anything that would otherwise require dumping
    raw text into your own context. Pass only the relevant slice in the prompt.
  • Standard libs: json, re, plus pandas/sqlite3 (import them).

Strategy:
  1. PROBE: list keys, check types, peek at headers — never print whole files.
  2. FILTER: use regex/SQL/pandas to narrow to the rows or text spans that
     matter for the task.
  3. DELEGATE: if a passage is dense (whitepaper section, audit finding), pass
     the slice to sub_lm with a precise question. Don't read it yourself.
  4. STITCH: combine sub_lm outputs into structured findings.
  5. FINALIZE: when done, set FINAL = {...} matching the OUTPUT SCHEMA.

Hard rules:
  • NEVER print > 4000 chars in one turn — the root context will choke.
  • NEVER paste large file contents into your reasoning. Refer by variable.
  • Keep code blocks short and incremental; one logical step per turn.
  • If a sub_lm reply is ambiguous, query again with a tighter prompt.
"""


def _format_manifest(environment: dict[str, Any]) -> str:
    """Describe what's in the REPL without printing contents."""
    lines = ["ENVIRONMENT MANIFEST (variables you can access in the REPL):"]
    for k, v in environment.items():
        if k.startswith("_"):
            continue
        try:
            t = type(v).__name__
            if hasattr(v, "shape"):
                size = f"shape={getattr(v, 'shape', None)}"
            elif isinstance(v, (str, bytes)):
                size = f"len={len(v)}"
            elif isinstance(v, (list, tuple, dict, set)):
                size = f"len={len(v)}"
            else:
                size = ""
            lines.append(f"  {k!s}: {t}  {size}")
        except Exception:
            lines.append(f"  {k!s}: <opaque>")
    return "\n".join(lines)


def _root_turn(
    history: list[dict],
    system: str,
    *,
    model: str,
    max_tokens: int = 2048,
) -> str:
    """One call to the root model. Returns its raw text."""
    from anthropic import Anthropic
    import os
    client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])
    msg = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        temperature=0.0,
        system=system,
        messages=history,
    )
    return "".join(b.text for b in msg.content if getattr(b, "type", None) == "text")


_CODE_RE = re.compile(r"```(?:python)?\s*\n(.*?)```", re.DOTALL)


def _extract_code(reply: str) -> Optional[str]:
    m = _CODE_RE.search(reply)
    return m.group(1).strip() if m else None


# ────────────────────────────────────────────────────────────────────────
# Public entry point.
# ────────────────────────────────────────────────────────────────────────

def run_rlm(
    *,
    agent_name: str,
    environment: dict[str, Any],
    task: str,
    output_schema: dict[str, str],
    max_iters: int = 12,
    model: str = DEFAULT_ROOT_MODEL,
    verbose: bool = False,
) -> dict[str, Any]:
    """
    Run an RLM analysis. Returns the dict the root assigned to FINAL.

    Parameters
    ----------
    agent_name : str
        Tag used in logs, e.g. "tokenomics".
    environment : dict
        Globals injected into the REPL. Typical keys:
          'token_symbol', 'tokenomics_df', 'unlock_schedule_text',
          'top_holders_csv', 'whitepaper_excerpt', 'db_path' (sqlite path).
        NOTE: large strings/dataframes are fine here — they live in the REPL,
        not in the root's context.
    task : str
        The analysis question, in natural language.
    output_schema : dict
        Field-name -> short description. Root model coerces FINAL to match.
    max_iters : int
        Hard cap on REPL turns (paper recommends ~10).
    """
    repl = _build_repl(environment)
    manifest = _format_manifest(environment)
    schema_lines = "\n".join(f"  - {k}: {v}" for k, v in output_schema.items())
    system = (
        _ROOT_SYSTEM
        + f"\n\nAGENT: {agent_name}\nTASK:\n{textwrap.indent(task, '  ')}\n"
        + f"\nOUTPUT SCHEMA (assign FINAL to a dict matching exactly these keys):\n{schema_lines}\n"
        + f"\n{manifest}\n"
    )

    history: list[dict] = [
        {
            "role": "user",
            "content": (
                "Begin the analysis. Probe the environment first, then proceed "
                "step-by-step. End with `FINAL = {...}` and `print('DONE')`."
            ),
        }
    ]

    for i in range(max_iters):
        reply = _root_turn(history, system, model=model)
        history.append({"role": "assistant", "content": reply})
        if verbose:
            print(f"\n--- iter {i} root ---\n{reply}\n")

        # Did the root finalize?
        final_val = repl.get("FINAL")
        if final_val is not None and isinstance(final_val, dict):
            return final_val

        code = _extract_code(reply)
        if not code:
            # Root spoke but didn't emit code — nudge it.
            history.append({
                "role": "user",
                "content": (
                    "Reply must be a python code block. Continue the analysis "
                    "by writing ```python … ```. If you are done, set FINAL."
                ),
            })
            continue

        stdout, error = _exec_code(code, repl)
        # Truncate stdout fed back to root, per the paper's guidance —
        # only constant-size metadata flows back.
        if len(stdout) > 4000:
            stdout = stdout[:4000] + "\n... [truncated]"
        feedback = stdout if not error else (stdout + "\n--- error ---\n" + error)
        if not feedback.strip():
            feedback = "(no output)"
        history.append({"role": "user", "content": f"REPL stdout:\n{feedback}"})

        # Did FINAL get set this turn?
        final_val = repl.get("FINAL")
        if final_val is not None and isinstance(final_val, dict):
            return final_val

    # Out of iterations — return whatever the root has in FINAL, or a stub.
    final_val = repl.get("FINAL")
    if isinstance(final_val, dict):
        return final_val
    return {
        "error": "max_iters_reached",
        "agent": agent_name,
        "iters": max_iters,
        "schema_keys": list(output_schema.keys()),
    }
